
server:
  port: PORT

spotify:
  clientId: SPOTIFY_CLIENT_ID
  clientSecret: SPOTIFY_CLIENT_SECRET
  redirectUri: SPOTIFY_REDIRECT_URI
  playlistUser: SPOTIFY_PLAYLIST_USER
  targetPlaylist: SPOTIFY_TARGET_PLAYLIST

slack:
  clientId: SLACK_CLIENT_ID
  clientSecret: SLACK_CLIENT_SECRET
  token: SLACK_TOKEN
  verificationToken: SLACK_VERIFICATION_TOKEN
  oAuthState: SLACK_OAUTH_STATE
  redirectUri: SLACK_REDIRECT_URI

mongo:
  host: MONGO_HOST
  port: MONGO_PORT
  db: MONGO_DB
